### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by hotfusion** [chjj/bns#40]
Hey, since python update `3.12`  the `distutils` module has been deprecated, because of that I am getting an error when I'm trying to install `bns` package. Here is the [[node-gyp](https://github.com/nodejs/node-gyp)](https://github.com/nodejs/node-gyp/issues/2869) GitHub repository to the problem. 

npm ERR! code 1
npm ERR! path C:\Users\xxx\applications\node\node_modules\bcrypto
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild  
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@19.0.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.12.0 found at "C:\Python312\python.exe"
npm ERR! gyp info find VS using VS2022 (17.5.33414.496) found at:
npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Python312\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\xxx\\applications\\node\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\xxx\\applications\\node\\node_modules\\bcrypto\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\xxx\\applications\\node\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\xxx\\AppData\\Local\\node-gyp\\Cache\\19.0.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\xxx\\AppData\\Local\\node-gyp\\Cache\\19.0.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\xxx\\applications\\node\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\xxx\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\19.0.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\xxx\\applications\\node\\node_modules\\bcrypto',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\xxx\\applications\\node\\node_modules\\bcrypto\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "C:\Users\xxx\applications\node\node_modules\node-gyp\gyp\gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "C:\Users\xxx\applications\node\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "C:\Users\xxx\applications\node\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\xxx\applications\node\node_modules\node-gyp\lib\configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Users\\xxx\\AppData\\Roaming\\nvm\\v19.0.0\\node.exe" "C:\\Users\\xxx\\applications\\node\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\xxx\applications\node\node_modules\bcrypto
npm ERR! gyp ERR! node -v v19.0.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Local\npm-cache\_logs\2023-11-02T18_54_17_595Z-debug-0.log

**Comment by rithvikvibhu** [comment]
node-gyp v10 fixes this, but v10 also drops support for node.js <18.17 and 19.

npm v10 updates its internal node-gyp to v10.

Node.js v20.7 ships with npm v10.

So, on a system with python 3.12, either:
- use node.js 18.17 and also update npm to v10
OR
- use node.js 20.7+ (update npm if not v10 already)
OR
- use node.js 20.0 - 20.6 and manually update npm's node-gyp - maybe with https://github.com/nodejs/node-gyp/blob/main/docs/Updating-npm-bundled-node-gyp.md idk if it still works

References:
- https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md
- https://github.com/npm/cli/releases/tag/v10.0.0
- https://github.com/nodejs/node-gyp/releases/tag/v10.0.0

**Comment by hotfusion** [comment]
Thanks

**Comment by AzonInc** [comment]
Same issue here.
I'm on a fresh Node v21.1.0 installation with NPM 10.2.2 and Python 3.12.0. However npm install errors and says node-gyp is still v9.4.1.

I tried to manually update node-gyp without success (https://github.com/nodejs/node-gyp/blob/main/docs/Updating-npm-bundled-node-gyp.md).

**9.4.0** in C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp
**10.0.1** in C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\run-script\node_modules\node-gyp
**10.0.1** in C:\Users\flori\AppData\Roaming\npm\node_modules\node-gyp
**3.0.0** in C:\Users\flori\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\node-gyp

So where is 9.4.1 now?
